/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#acc7ff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#00201d",
        "surface-dim": "#ccdbf3",
        "surface-tint": "#425e92",
        "primary-fixed": "#d7e2ff",
        "primary-container": "#163668",
        "on-error": "#ffffff",
        "tertiary-fixed": "#89f5e7",
        "secondary-fixed": "#ffdbcf",
        "surface-bright": "#f8f9ff",
        "outline": "#747780",
        "on-background": "#0d1c2e",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed-variant": "#005049",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "on-secondary-container": "#531800",
        "on-primary-container": "#84a0d9",
        "error": "#ba1a1a",
        "tertiary": "#002723",
        "inverse-primary": "#acc7ff",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#44474f",
        "surface-container": "#e6eeff",
        "tertiary-container": "#003f39",
        "secondary": "#a83900",
        "on-secondary-fixed": "#380d00",
        "on-tertiary-container": "#3fb1a5",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#001a40",
        "on-secondary-fixed-variant": "#802a00",
        "on-secondary": "#ffffff",
        "surface-variant": "#d5e3fc",
        "primary": "#00204c",
        "on-surface": "#0d1c2e",
        "inverse-surface": "#233144",
        "secondary-container": "#fc6018",
        "on-primary-fixed-variant": "#294679",
        "background": "#f8f9ff",
        "surface-container-highest": "#d5e3fc",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6d0"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-48": "3rem",
        "space-24": "1.5rem",
        "space-16": "1rem",
        "space-4": "0.25rem",
        "space-32": "2rem",
        "margin-edge": "1.5rem",
        "space-8": "0.5rem",
        "space-20": "1.25rem",
        "gutter": "1rem",
        "space-2": "0.125rem",
        "space-12": "0.75rem",
        "space-64": "4rem"
      },
      "fontFamily": {
        "label-md": ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-block": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "code-block": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
